export const MonitorData = [
    {
        id: 3,
        name: "L'ak",
        commune: "L'ak",
        district: "Ou Chum",
        province: "Ratanak Kiri",
        sensorId: 4734,
        count: 1,
        kind: "New constructed well (Plan)",
        type: "Afridev",
        cellular: "",
        bluetooth: 1,
        training: "",
        remark: "",
        dataFinished: "17-Oct-16",
        depth: 47,
        yield: 2,
        static: 20,
        dynamic: 27,
        quality: "Acceptable"
    },
    {
        id: 6,
        name: "L'ak",
        commune: "L'ak",
        district: "Ou Chum",
        province: "Ratanak Kiri",
        sensorId: 4762,
        count: 1,
        kind: "Rehabilitated Well",
        type: "Afridev",
        cellular: "",
        bluetooth: 1,
        training: 1,
        remark: "",
        dataFinished: 2016,
        depth: 34,
        yield: 2,
        static: 20,
        dynamic: 30,
        quality: "Acceptable"
    },
    {
        id: 7,
        name: "Kouk (Ampil)",
        commune: "L'ak",
        district: "Ou Chum",
        province: "Ratanak Kiri",
        sensorId: 4736,
        count: 1,
        kind: "New constructed well (SVC)",
        type: "Afridev",
        cellular: "1",
        bluetooth: "",
        training: 1,
        remark: "",
        dataFinished: "19-Sep-18",
        depth: 45,
        yield: 2,
        static: 18,
        dynamic: 29,
        quality: "Acceptable"
    },
    {
        id: 8,
        name: "Kouk (Pouy)",
        commune: "L'ak",
        district: "Ou Chum",
        province: "Ratanak Kiri",
        sensorId: 4742,
        count: 1,
        kind: "Rehabilitated well (Plan)",
        type: "Afridev",
        cellular: "",
        bluetooth: 1,
        training: 1,
        remark: "",
        dataFinished: 2014,
        depth: 60,
        yield: 1.5,
        static: 30,
        dynamic: 45,
        quality: "Acceptable"
    },
    {
        id: 17,
        name: "Ta Nga",
        commune: "Nhang",
        district: "Andoung Meas",
        province: "Ratanak Kiri",
        sensorId: 4760,
        count: 1,
        kind: "New constructed well (plan)",
        type: "Afridev",
        cellular: "",
        bluetooth: 1,
        training: 1,
        remark: "",
        dataFinished: 2015,
        depth: 30,
        yield: 1.5,
        static: 15,
        dynamic: 25,
        quality: "Acceptable"
    },
    {
        id: 37,
        name: "Khnar Rungvas",
        commune: "Khun Ream",
        district: "Banteay Srei",
        province: "Siem Reap",
        sensorId: 4763,
        count: 1,
        kind: "New constructed well (plan)",
        type: "Afridev",
        cellular: "1",
        bluetooth: "",
        training: 1,
        remark: "Group 3",
        dataFinished: "12/8/2016",
        depth: 32,
        yield: 1,
        static: 2,
        dynamic: 20,
        quality: "Acceptable"
    },
    {
        id: 38,
        name: "Khun Ream",
        commune: "Khun Ream",
        district: "Banteay Srei",
        province: "Siem Reap",
        sensorId: 4764,
        count: 1,
        kind: "New constructed well (plan)",
        type: "Afridev",
        cellular: "",
        bluetooth: 1,
        training: 1,
        remark: "",
        dataFinished: 2016,
        depth: 33,
        yield: 1.5,
        static: 3,
        dynamic: 18,
        quality: "Acceptable"
    },
    {
        id: 40,
        name: "Khun Ream",
        commune: "Khun Ream",
        district: "Banteay Srei",
        province: "Siem Reap",
        sensorId: 4715,
        count: 1,
        kind: "New constructed well (plan)",
        type: "Afridev",
        cellular: "1",
        bluetooth: "",
        training: 1,
        remark: "",
        dataFinished: 2009,
        depth: 32,
        yield: "No",
        static: 3,
        dynamic: 24,
        quality: "Acceptable"
    },
];